from setuptools import find_packages, setup

setup(
    name="DRANetSplicer",
    version="1.0",
    author="Xueyan Liu",
    author_email="",
    description="A splice site prediction model based on deep residual attention networks",
    long_description=open("README.md", "r", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    keywords=["Genomics", "Deep Learning", "Tensorflow", "Keras"],
    url="https://github.com/XueyanLiu-creator/DRANetSplicer",
    package_dir={"": "src"},
    packages=find_packages("src"),
    install_requires=[
        "numpy>=1.19.5",
        "pandas",
        "matplotlib",
        "tqdm>4.25.0",
        "scikit-learn",
        "shap>=0.41.0",
        "opencv-python",
        "keras==2.6.0",
        "protobuf >=3.9.2, <=3.20.3",
        "tensorflow-gpu==2.6.0",
    ],
    python_requires=">=3.7.0",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Intended Audience :: Education",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Operating System :: Linux",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
)
